# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller
    - joint_trajectory_controller

  scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_ur3_shoulder_pan_joint
      - right_ur3_shoulder_lift_joint
      - right_ur3_elbow_joint
      - right_ur3_wrist_1_joint
      - right_ur3_wrist_2_joint
      - right_ur3_wrist_3_joint

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: false
    joints:
      - right_ur3_shoulder_pan_joint
      - right_ur3_shoulder_lift_joint
      - right_ur3_elbow_joint
      - right_ur3_wrist_1_joint
      - right_ur3_wrist_2_joint
      - right_ur3_wrist_3_joint