# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    right_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_manipulator_controller:
  ros__parameters:
    joints:
      - right_ur3_shoulder_pan_joint
      - right_ur3_shoulder_lift_joint
      - right_ur3_elbow_joint
      - right_ur3_wrist_1_joint
      - right_ur3_wrist_2_joint
      - right_ur3_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_manipulator_controller:
  ros__parameters:
    joints:
      - left_ur3_shoulder_pan_joint
      - left_ur3_shoulder_lift_joint
      - left_ur3_elbow_joint
      - left_ur3_wrist_1_joint
      - left_ur3_wrist_2_joint
      - left_ur3_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity